### ISSUE TITLE
[UI] implement "Community Care Section" 

### ISSUE THREAD

**Issue by Khadeeejah** [Chimoney/Community-Website#10]
Implement the community care section

[Figma](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=233%3A688&t=fMbtxmVcO2YETJ1i-4)

**Comment by grand-rick001** [comment]
I can work on this @Khadeeejah @phyleria

**Comment by phyleria** [comment]
Sure, go ahead!

**Comment by phyleria** [comment]
Hi @grand-rick001 
Reopening this issue because I realized it is not responsive on mobile. The Community care design overlaps with the blogs section. Kindly let me know if you can work on correcting this
