### ISSUE TITLE
[UI] Implement Make value card

### ISSUE THREAD

**Issue by Khadeeejah** [Chimoney/Community-Website#11]
Implement the make value card on the footer section
[figma](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=220%3A128&t=EspXSQbzNIhl4c69-4)

**Comment by phyleria** [comment]
I'll let @Khadeeejah answer that 👍🏾

**Comment by Khadeeejah** [comment]
> Is it the card that says `make value move today`?. If so, I can be assigned and work on it @Khadeeejah @phyleria

yes please

**Comment by grand-rick001** [comment]
> > Is it the card that says `make value move today`?. If so, I can be assigned and work on it @Khadeeejah @phyleria
> 
> yes please

Alright, I can work on it
