### ISSUE TITLE
[UI] Implement the footer section

### ISSUE THREAD

**Issue by Khadeeejah** [Chimoney/Community-Website#12]
Implement the footer section
Ensure all links to the social media platforms are correctly embedded
Use Js to implement the copyright section

[figma](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=220%3A128&t=fMbtxmVcO2YETJ1i-4)

**Comment by eligifty-coder** [comment]
Can this be assigned to me

**Comment by eligifty-coder** [comment]
@Khadeeejah , @phyleria

**Comment by phyleria** [comment]
Sure, please go ahead!
