### ISSUE TITLE
Chimoney Website Design  

### ISSUE THREAD

**Issue by elegant1T** [Chimoney/Community-Website#2]
This stage requires a UI/UX design of what the community site project would look like. 

As a product designer, using any template of your choice, while noting and following the [Brand Guidelines](https://docs.google.com/document/d/11Niq7-F96alud7s9S08km22MJ5bS2ZYF_xbiJSX8o4I/edit?usp=sharing). 

Do produce a website design that the developers work with.

**Comment by warisakorede** [comment]
Here's the Figma link to the website 

https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=3%3A2&t=EhR8Lv3FiJOaXxOi-1

Make sure to send me your email on Chimoney's discord server to give you the edit access

**Comment by phyleria** [comment]
Closing this issue, since we already have the design 👍🏾
