### ISSUE TITLE
Create a Static Chimoney Community Website

### ISSUE THREAD

**Issue by elegant1T** [Chimoney/Community-Website#3]
The Chimoney Community Site is a project that aims to recognize the contributions of the Chimoney community members (ChiMers). This site will act as a content hub for the blog, videos, documentation and events created within the Community and by ChiMers.

With the merged website design in #2, build the Chimoney Community Website.

Note: This should be static site for now.

**Comment by CatherineKiiru** [comment]
Is this issue still open? I'd like to work on it

**Comment by CatherineKiiru** [comment]
Hi @phyleria is this issue still available? I'd like to work on it

**Comment by phyleria** [comment]
Hi @CatherineKiiru !
Thank you for your request, unfortunately this issue isn't valid(I forgot to remove it)
It was meant for the whole community site which we're almost done with.
Kindly pick one of the other issues instead.
