### ISSUE TITLE
Change Website font to Poppins

### ISSUE THREAD

**Issue by phyleria** [Chimoney/Community-Website#34]

**Comment by Sarthak0006** [comment]
Hello, 
I can change the website font to 'Poppins'. Please tell me you want to change whole website font to Poppins or in some selected text.


![font-family: 'Poppins'](https://user-images.githubusercontent.com/117128614/228607585-7236d46a-4b5f-4c00-a29f-d487b4957599.png)

**Comment by phyleria** [comment]
Hi @Sarthak0006 
We intended for the whole website font to be changed to Poppins 👍🏾

**Comment by Sarthak0006** [comment]
So please assign it to me so i can start work on it

**Comment by phyleria** [comment]
Sure I have assigned it to you 👍🏾
