### ISSUE TITLE
Create content for the Chimoney community site

### ISSUE THREAD

**Issue by elegant1T** [Chimoney/Community-Website#4]
The Chimoney Community Site is a project that aims to recognize the contributions of the Chimoney community members (ChiMers). This site will act as a content hub for the blog, videos, documentation and events created within the Community and by ChiMers.

This stage will involve technical writers, bloggers and content creators working together to populate the site. 
You can create content that will be befitting for upload on the community website #3. Content can be: 

- Documentation (Chimoney, community, programs and initiatives)
- Videos (Chimoney, community, programs and initiatives)
- Any other content format you can come up with. 

Once the initial Community site is done, the various contents for different sections will be added to the community Site.

**Comment by Ajiboso-Adeola** [comment]
I would love  to work on this issue

**Comment by phyleria** [comment]
Hi @Ajiboso-Adeola 
What specific content would you like to work on?
Feel free to pick any of the issues labeled content. I will close this one now since smaller issues have been created from it. Thank you!
