### ISSUE TITLE
Fix Hanging Footer

### ISSUE THREAD

**Issue by phyleria** [Chimoney/Community-Website#47]

**Comment by tan911** [comment]
Assign this to me, I would love to fix it.

**Comment by phyleria** [comment]
Sure, go ahead

**Comment by tan911** [comment]
Thanks, but I just want to clarify the issue, is this the thing that need to be fix? Thank you.
![issuehml](https://user-images.githubusercontent.com/92535526/235442452-d58d5933-5eea-4b7f-826a-dd5568de2241.png)

**Comment by phyleria** [comment]
Yes it is 👍🏾
