### ISSUE TITLE
[UI] Navbar Implementation

### ISSUE THREAD

**Issue by Khadeeejah** [Chimoney/Community-Website#5]
Implement the Navbar 

[Figma design](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=230%3A188&t=fMbtxmVcO2YETJ1i-4)

**Comment by minhaj-313** [comment]
@Khadeeejah Please Merge My PR i did added Responsive Navbar

**Comment by Khadeeejah** [comment]
> I would love to take up this issue

Okay go ahead I'll assign it to you

**Comment by Sarthak0006** [comment]
but i made navbar along with Hero Section.

![navbar](https://user-images.githubusercontent.com/117128614/229112274-63001663-d333-4baa-b681-0afb808a24db.png)

**Comment by Khadeeejah** [comment]
> but i made navbar along with Hero Section.
> 
> 
> 
> ![navbar](https://user-images.githubusercontent.com/117128614/229112274-63001663-d333-4baa-b681-0afb808a24db.png)
> 
> 

Hi no you can't make navbar withthe hero
It's one pr per issue please
Thank you

**Comment by ibimina** [comment]
@Khadeeejah can I work on the navbar, it's not responsive on smaller screens

**Comment by phyleria** [comment]
Hi @ibimina 
Yes please go ahead!

**Comment by ibimina** [comment]
@phyleria the figma design doesn't show what the navigation looks like when the hamburger menu is clicked,
Please can you help with the design or where can I can them I have checked with the figma link above

**Comment by phyleria** [comment]
Let me kindly check with the design team @ibimina

**Comment by phyleria** [comment]
Hi @ibimina 
Sorry for the delayed response but the hamburger menu design has been updated now - https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?type=design&node-id=220-129&mode=design

**Comment by Sarthak0006** [comment]
I want to code this hamburger menu design, Please assign this issue to me.

**Comment by phyleria** [comment]
Assigning it to you. Thanks @Sarthak0006
