### ISSUE TITLE
fix the last use button on the login page.

### ISSUE THREAD

**Issue by harshsinghcs** [Chimoney/Community-Website#58]
![image](https://github.com/Chimoney/Community-Website/assets/115187902/ff5d102b-333e-49ba-a9e4-85127367a8a1)

**Comment by harshsinghcs** [comment]
assign me this issue under hacktoberfest  @Khadeeejah  and @phyleria

**Comment by phyleria** [comment]
Hi @harshsinghcs 
 
Unfortunately you can't work on this issue because the code is private.

**Comment by harshsinghcs** [comment]
> Hi @harshsinghcs 
>  
> Unfortunately you can't work on this issue because the code is private.

Right
But ma'am if you want I'll work on it.
