### ISSUE TITLE
To change twitter logo as X

### ISSUE THREAD

**Issue by ayan-joshi** [Chimoney/Community-Website#59]
As the twitter logo is changed I would like to make change in the website.
I will add the new twitter logo !

Assign me the issue if u like my idea @phyleria

**Comment by ayan-joshi** [comment]
@phyleria have a look

**Comment by phyleria** [comment]
Hi @ayan-joshi 

Which line would you like to make the changes to?

**Comment by ayan-joshi** [comment]
![Screenshot 2023-10-19 175609](https://github.com/Chimoney/Community-Website/assets/96243602/4ac9c30c-3cb5-4b0f-819c-ca8abe7a7b5d)

This twitter logo is old we can change it to the new one

**Comment by phyleria** [comment]
Ok, go ahead

**Comment by octocatblain** [comment]
Hi, @phyleria and @Khadeeejah I would like to work on this issue since it seems it hasn't been worked on yet even though it was assigned someone. I will be happy to help.

**Comment by phyleria** [comment]
Go ahead @octocatblain 👍🏾
