### ISSUE TITLE
Footer Content 

### ISSUE THREAD

**Issue by octocatblain** [Chimoney/Community-Website#64]
- The footer content is wrapped or doesn't have enough width. See visual below.

- **Bug visual:**
![Screenshot from 2024-03-01 15-20-07](https://github.com/Chimoney/Community-Website/assets/62080362/b45cb9a2-a00f-4e13-a1eb-7e34064d3030)

- **Figma layout:**
![Screenshot from 2024-03-01 15-20-52](https://github.com/Chimoney/Community-Website/assets/62080362/f7723ab7-d88a-4e0e-aac6-fcf868b41076)

@Khadeeejah @phyleria kindly assign.

**Comment by phyleria** [comment]
Sure, go ahead
