### ISSUE TITLE
feat: Update Chipay to Payout in products section on the website

### ISSUE THREAD

**Issue by Lymah123** [Chimoney/Community-Website#69]
## 👋 Welcome!

Welcome to Chimoney's open-source community! This issue is specifically designed for first-time contributors, so if you're new to open source or haven't contributed to our codebase before, you're in the right place. We're here to help you take your first steps and guide you through the process of making your first contribution.

## What You'll Need to Know

You don't need any prior knowledge or experience to work on this issue. We're here to support you every step of the way, so don't hesitate to ask questions if you're unsure about anything.

## Problem

Currently, under the products section, we have Chipay, we'd like to update it to Payout.

For easy navigation, take a look at the screenshot below.

![image](https://github.com/Chimoney/Community-Website/assets/109049037/774cbd0f-c263-4792-bec9-5a413f85f375)

## 📋 Step by Step

1. **Claim this issue:** Comment below to claim this issue. If someone else has already claimed it, feel free to ask if they've started working on it or if they need any help.
  
2. **Make the changes**
  
3. **Commit your changes:** Once you've made the necessary updates, commit your changes and then submit a pull request so we can review your changes and merge them into the main codebase.

## 💬 Keep Us Updated

We encourage you to keep us updated on your progress. If you encounter any challenges or need assistance, don't hesitate to ask for help. We're here to support you throughout the process.

## 👥 Collaboration

If you see someone else working on this issue or if you'd like to collaborate with others, feel free to reach out and offer your assistance. Collaboration is key to our success as a community!

## ❓ Questions?

If you have any questions or need clarification on anything, please leave a comment below. We're here to help!

**Comment by moosecodes** [comment]
I would like to claim this issue.

**Comment by Lymah123** [comment]
Hi @moosecodes , it has been assigned to you.
