### ISSUE TITLE
[UI] Implement "as part of the community " section

### ISSUE THREAD

**Issue by Khadeeejah** [Chimoney/Community-Website#8]
Implement the first section directly after the hero section

[figma url](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=233%3A522&t=fMbtxmVcO2YETJ1i-4)

**Comment by AndroGenius-codes** [comment]
Can I work on this

**Comment by Khadeeejah** [comment]
Yes please

**Comment by Sarthak0006** [comment]
I Can make it please give it to me. i am working on it.

![Screenshot from 2023-04-01 17-35-01](https://user-images.githubusercontent.com/117128614/229287648-a7bebdde-ab8a-476e-b537-dcf78f1c9144.png)

**Comment by AndroGenius-codes** [comment]
> I Can make it please give it to me. i am working on it.
> 
> ![Screenshot from 2023-04-01 17-35-01](https://user-images.githubusercontent.com/117128614/229287648-a7bebdde-ab8a-476e-b537-dcf78f1c9144.png)

You can work on it no problem
