### ISSUE TITLE
[UI] Implement featured post section

### ISSUE THREAD

**Issue by Khadeeejah** [Chimoney/Community-Website#9]
One or more people are welcome to work on this section as its the largest part of the landing page

[figma](https://www.figma.com/file/TOZC54ULBuHUA1EU5tZK3k/Chimoney-Community-Website-Design-Contributions?node-id=220%3A128&t=s3IuCjGbDipyN9I5-0)

**Comment by AndroGenius-codes** [comment]
Hi good evening, I'd like to work on this
